######################################################################
# Automatically generated by qmake (3.0) ??? ??? 3 16:16:21 2018
######################################################################

TEMPLATE = app
TARGET = cellular
INCLUDEPATH += .

# Input
HEADERS += board.h
SOURCES += board.cpp main.cpp

QT += widgets
CONFIG += c++11
